<?php

use yii\db\Migration;

/**
 * Class m210705_150004_add_athena_users
 */
class m990101_000000_add_total_quantities_medications extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

        Yii::$app->db->createCommand()->batchInsert('total_quantity_units', ['quantityunit'], [
    ['0.05 mL syringe(s)'],
    ['0.05 mL vial(s)'],
    ['0.1 mL kit(s)'],
    ['0.1 mL syringe(s)'],
    ['0.1 mL vial(s)'],
    ['0.13 mL syringe(s)'],
    ['0.15 mL syringe(s)'],
    ['0.2 mL syringe(s)'],
    ['0.2 mL vial(s)'],
    ['0.25 mL ampul(s)'],
    ['0.25 mL syringe(s)'],
    ['0.3 mL syringe(s)'],
    ['0.35 mL syringe(s)'],
    ['0.375 mL syringe(s)'],
    ['0.4 mL syringe(s)'],
    ['0.4 mL vial(s)'],
    ['0.42 mL cartridge(s)'],
    ['0.42 mL syringe(s)'],
    ['0.45 mL syringe(s)'],
    ['0.45 mL vial(s)'],
    ['0.5 mL ampul(s)'],
    ['0.5 mL cartridge(s)'],
    ['0.5 mL syringe(s)'],
    ['0.5 mL vial(s)'],
    ['0.51 mL syringe(s)'],
    ['0.55 mL syringe(s)'],
    ['0.6 mL syringe(s)'],
    ['0.6 mL vial(s)'],
    ['0.65 mL syringe(s)'],
    ['0.67 mL syringe(s)'],
    ['0.7 mL syringe(s)'],
    ['0.7 mL vial(s)'],
    ['0.72 mL syringe(s)'],
    ['0.75 mL cartridge(s)'],
    ['0.75 mL kit(s)'],
    ['0.75 mL syringe(s)'],
    ['0.78 mL cartridge(s)'],
    ['0.8 mL syringe(s)'],
    ['0.8 mL vial(s)'],
    ['0.83 mL syringe(s)'],
    ['0.85 mL syringe(s)'],
    ['0.85 mL vial(s)'],
    ['0.875 mL syringe(s)'],
    ['0.9 mL syringe(s)'],
    ['0.98 mL cartridge(s)'],
    ['0.98 mL syringe(s)'],
    ['1 gm jar(s)'],
    ['1 gm packet(s)'],
    ['1 gm pf appli(s)'],
    ['1 gm tube(s)'],
    ['1 mL aer ref(s)'],
    ['1 mL aer w/adap(s)'],
    ['1 mL ampul(s)'],
    ['1 mL bottle(s)'],
    ['1 mL cartridge(s)'],
    ['1 mL drop btl(s)'],
    ['1 mL jar(s)'],
    ['1 mL pf appli(s)'],
    ['1 mL syringe(s)'],
    ['1 mL tube(s)'],
    ['1 mL vial(s)'],
    ['1.05 mL kit(s)'],
    ['1.1 mL syringe(s)'],
    ['1.125 gm pf appli(s)'],
    ['1.14 mL syringe(s)'],
    ['1.17 mL cartridge(s)'],
    ['1.17 mL syringe(s)'],
    ['1.2 mL cartridge(s)'],
    ['1.2 mL syringe(s)'],
    ['1.2 mL vial(s)'],
    ['1.25 gm packet(s)'],
    ['1.25 gm pf appli(s)'],
    ['1.25 mL syringe(s)'],
    ['1.25 mL vial(s)'],
    ['1.3 mL vial(s)'],
    ['1.315 mL syringe(s)'],
    ['1.33 mL vial(s)'],
    ['1.5 mL cartridge(s)'],
    ['1.5 mL drop btl(s)'],
    ['1.5 mL glass cont(s)'],
    ['1.5 mL syringe(s)'],
    ['1.5 mL vial(s)'],
    ['1.56 mL box(s)'],
    ['1.6 mL syringe(s)'],
    ['1.6 mL vial(s)'],
    ['1.7 gm cartridge(s)'],
    ['1.7 mL cartridge(s)'],
    ['1.7 mL drop btl(s)'],
    ['1.7 mL pf appli(s)'],
    ['1.7 mL vial(s)'],
    ['1.75 mL syringe(s)'],
    ['1.8 mL cartridge(s)'],
    ['1.8 mL vial(s)'],
    ['1.9 mL syringe(s)'],
    ['10 gm bottle(s)'],
    ['10 gm can(s)'],
    ['10 gm packet(s)'],
    ['10 gm tube(s)'],
    ['10 mL ampul(s)'],
    ['10 mL blist pack(s)'],
    ['10 mL bottle(s)'],
    ['10 mL box(s)'],
    ['10 mL canister(s)'],
    ['10 mL cup(s)'],
    ['10 mL drop btl(s)'],
    ['10 mL packet(s)'],
    ['10 mL pf appli(s)'],
    ['10 mL syringe(s)'],
    ['10 mL vial(s)'],
    ['10 mL vial/kit(s)'],
    ['10.15 mL cup(s)'],
    ['10.2 gm aer w/adap(s)'],
    ['10.3 mL drop btl(s)'],
    ['10.6 gm aer br.act(s)'],
    ['10.6 gm aer w/adap(s)'],
    ['10.6 gm canister(s)'],
    ['10.7 gm aer w/adap(s)'],
    ['10.7 gm canister(s)'],
    ['10.8 mL bottle(s)'],
    ['100 gm bottle(s)'],
    ['100 gm can(s)'],
    ['100 gm canister(s)'],
    ['100 gm jar(s)'],
    ['100 gm tube(s)'],
    ['100 mL bag(s)'],
    ['100 mL bottle(s)'],
    ['100 mL box(s)'],
    ['100 mL cartridge(s)'],
    ['100 mL flex cont(s)'],
    ['100 mL glass cont(s)'],
    ['100 mL squeez btl(s)'],
    ['100 mL syringe(s)'],
    ['100 mL tube(s)'],
    ['100 mL vial(s)'],
    ['1000 gm jar(s)'],
    ['1000 mL bag(s)'],
    ['1000 mL bottle(s)'],
    ['1000 mL can(s)'],
    ['1000 mL flex cont(s)'],
    ['101.4 mL kit(s)'],
    ['1026 mL bag(s)'],
    ['103 mL tube(s)'],
    ['104 mL bottle(s)'],
    ['104 mL squeez btl(s)'],
    ['104 mL tube(s)'],
    ['1040 gm jar(s)'],
    ['1043 gm jar(s)'],
    ['1047 mL bag(s)'],
    ['105 gm jar(s)'],
    ['105 mL bottle(s)'],
    ['105 mL squeez btl(s)'],
    ['105 mL vial(s)'],
    ['1052.8 mL bag(s)'],
    ['106 gm tube(s)'],
    ['106 mL bag(s)'],
    ['107 gm jar(s)'],
    ['108 gm jar(s)'],
    ['11 mL syringe(s)'],
    ['11 mL vial(s)'],
    ['11.1 mL aer w/adap(s)'],
    ['11.1 mL vial(s)'],
    ['11.6 mL amp w/dev(s)'],
    ['11.6 mL ampul(s)'],
    ['11.7 gm aer w/adap(s)'],
    ['11.7 mL vial(s)'],
    ['11.9 gm tube(s)'],
    ['110 gm bottle(s)'],
    ['110 gm jar(s)'],
    ['110 mL bag(s)'],
    ['112 gm bottle(s)'],
    ['112 gm tube(s)'],
    ['112 mL bottle(s)'],
    ['112.5 gm tube(s)'],
    ['113 gm aer w/adap(s)'],
    ['113 gm bottle(s)'],
    ['113 gm can(s)'],
    ['113 gm canister(s)'],
    ['113 gm jar(s)'],
    ['113 gm tube(s)'],
    ['113 mL bottle(s)'],
    ['113 mL box(s)'],
    ['113.3 gm can(s)'],
    ['113.3 gm tube(s)'],
    ['113.4 gm bottle(s)'],
    ['113.4 gm can(s)'],
    ['113.4 gm jar(s)'],
    ['113.4 gm squeez btl(s)'],
    ['113.4 gm tube(s)'],
    ['113.6 gm jar(s)'],
    ['114 gm bottle(s)'],
    ['114 gm jar(s)'],
    ['114 gm tube(s)'],
    ['115 mL bag(s)'],
    ['115 mL bottle(s)'],
    ['115 mL canister(s)'],
    ['1150 mL bag(s)'],
    ['116 gm bottle(s)'],
    ['116 mL canister(s)'],
    ['116 mL squeez btl(s)'],
    ['117 gm tube(s)'],
    ['118 gm jar(s)'],
    ['118 mL bottle(s)'],
    ['118 mL box(s)'],
    ['118 mL jar(s)'],
    ['118 mL squeez btl(s)'],
    ['118 mL tube(s)'],
    ['118.28 mL bottle(s)'],
    ['118.28 mL kit(s)'],
    ['118.29 mL tube(s)'],
    ['118.3 mL bottle(s)'],
    ['118.5 mL bottle(s)'],
    ['119 gm bottle(s)'],
    ['119 gm jar(s)'],
    ['1191 gm jar(s)'],
    ['12 gm aer w/adap(s)'],
    ['12 gm bottle(s)'],
    ['12 gm canister(s)'],
    ['12 gm tube(s)'],
    ['12 mL bottle(s)'],
    ['12 mL drop btl(s)'],
    ['12 mL tube(s)'],
    ['12 mL vial(s)'],
    ['12.5 gm squeez btl(s)'],
    ['12.5 gm tube(s)'],
    ['12.5 mL cup(s)'],
    ['12.5 mL vial(s)'],
    ['12.51 gm bottle(s)'],
    ['12.9 gm aer w/adap(s)'],
    ['120 gm bag(s)'],
    ['120 gm bottle(s)'],
    ['120 gm canister(s)'],
    ['120 gm jar(s)'],
    ['120 gm tube(s)'],
    ['120 mL bag(s)'],
    ['120 mL bottle(s)'],
    ['120 mL box(s)'],
    ['120 mL cup(s)'],
    ['120 mL drop btl(s)'],
    ['120 mL jar(s)'],
    ['120 mL packet(s)'],
    ['120 mL squeez btl(s)'],
    ['120 mL tube(s)'],
    ['120.49 gm tube(s)'],
    ['1200 gm bottle(s)'],
    ['1200 mL packet(s)'],
    ['121 gm tube(s)'],
    ['122 gm jar(s)'],
    ['124 mL tube(s)'],
    ['125 mL bag(s)'],
    ['125 mL bottle(s)'],
    ['125 mL can(s)'],
    ['125 mL canister(s)'],
    ['125 mL jar(s)'],
    ['125 mL packet(s)'],
    ['125 mL syringe(s)'],
    ['125 mL tube(s)'],
    ['125 mL vial(s)'],
    ['1254 gm jar(s)'],
    ['126 mL bottle(s)'],
    ['126 mL can(s)'],
    ['127 gm bottle(s)'],
    ['127 gm canister(s)'],
    ['127 gm squeez btl(s)'],
    ['127 gm tube(s)'],
    ['128 gm bottle(s)'],
    ['13 gm aer w/adap(s)'],
    ['13 gm canister(s)'],
    ['13 gm tube(s)'],
    ['13 mL bottle(s)'],
    ['13 mL squeez btl(s)'],
    ['13 mL vial(s)'],
    ['13.4 mL vial(s)'],
    ['130 gm bottle(s)'],
    ['130 gm can(s)'],
    ['130 gm canister(s)'],
    ['130 gm jar(s)'],
    ['130 gm kit(s)'],
    ['130 mL bag(s)'],
    ['130 mL bottle(s)'],
    ['130 mL packet(s)'],
    ['133 gm bottle(s)'],
    ['133 gm canister(s)'],
    ['133 mL bottle(s)'],
    ['133 mL squeez btl(s)'],
    ['135 gm box(s)'],
    ['135 mL bottle(s)'],
    ['136 mL bottle(s)'],
    ['136 mL box(s)'],
    ['136 mL packet(s)'],
    ['1368 gm jar(s)'],
    ['14 gm bottle(s)'],
    ['14 gm jar(s)'],
    ['14 gm tube(s)'],
    ['14 mL bottle(s)'],
    ['14 mL vial(s)'],
    ['14.1 gm jar(s)'],
    ['14.1 gm tube(s)'],
    ['14.18 gm tube(s)'],
    ['14.2 gm packet(s)'],
    ['14.2 gm tube(s)'],
    ['14.7 mL bottle(s)'],
    ['14.7 mL squeez btl(s)'],
    ['140 gm bottle(s)'],
    ['140 gm jar(s)'],
    ['140 gm tube(s)'],
    ['140 mL bag(s)'],
    ['141 gm jar(s)'],
    ['141 gm tube(s)'],
    ['141.7 gm tube(s)'],
    ['141.8 gm bottle(s)'],
    ['141.8 gm squeez btl(s)'],
    ['142 gm bottle(s)'],
    ['142 gm can(s)'],
    ['142 gm jar(s)'],
    ['142 gm squeez btl(s)'],
    ['142 gm tube(s)'],
    ['142 mL bottle(s)'],
    ['1422 mL bottle(s)'],
    ['144 gm canister(s)'],
    ['144 gm tube(s)'],
    ['1440 mL bag(s)'],
    ['147 mL bottle(s)'],
    ['148 gm bottle(s)'],
    ['148 mL bottle(s)'],
    ['149.97 gm bottle(s)'],
    ['15 gm aer w/adap(s)'],
    ['15 gm bottle(s)'],
    ['15 gm box(s)'],
    ['15 gm can(s)'],
    ['15 gm canister(s)'],
    ['15 gm cup(s)'],
    ['15 gm jar(s)'],
    ['15 gm packet(s)'],
    ['15 gm pf appli(s)'],
    ['15 gm squeez btl(s)'],
    ['15 gm tube(s)'],
    ['15 mL aer w/adap(s)'],
    ['15 mL ampul(s)'],
    ['15 mL ampul/kit(s)'],
    ['15 mL bottle(s)'],
    ['15 mL canister(s)'],
    ['15 mL cup(s)'],
    ['15 mL drop btl(s)'],
    ['15 mL kit(s)'],
    ['15 mL packet(s)'],
    ['15 mL squeez btl(s)'],
    ['15 mL syringe(s)'],
    ['15 mL tube(s)'],
    ['15 mL vial(s)'],
    ['15.8 mL aer w/adap(s)'],
    ['150 gm bottle(s)'],
    ['150 gm can(s)'],
    ['150 gm canister(s)'],
    ['150 gm jar(s)'],
    ['150 gm tube(s)'],
    ['150 mL bag(s)'],
    ['150 mL bottle(s)'],
    ['150 mL drop btl(s)'],
    ['150 mL flex cont(s)'],
    ['150 mL vial(s)'],
    ['150.2 gm can(s)'],
    ['1500 mL bag(s)'],
    ['1500 mL bottle(s)'],
    ['1500 mL flex cont(s)'],
    ['151 gm canister(s)'],
    ['152 gm canister(s)'],
    ['1530 gm bottle(s)'],
    ['1540 mL bag(s)'],
    ['155 gm jar(s)'],
    ['155 gm tube(s)'],
    ['156 gm bottle(s)'],
    ['156 gm tube(s)'],
    ['158 mL bottle(s)'],
    ['159 gm kit(s)'],
    ['159 gm tube(s)'],
    ['16 gm aer w/adap(s)'],
    ['16 gm tube(s)'],
    ['16 mL aer w/adap(s)'],
    ['16 mL vial(s)'],
    ['16.7 mL vial(s)'],
    ['16.9 mL bottle(s)'],
    ['160 mL bag(s)'],
    ['160 mL bottle(s)'],
    ['165 gm box(s)'],
    ['17 gm bottle(s)'],
    ['17 gm canister(s)'],
    ['17 gm tube(s)'],
    ['17 mL drop btl(s)'],
    ['17 mL syringe(s)'],
    ['17 mL vial(s)'],
    ['17.5 mL vial(s)'],
    ['170 gm aer w/adap(s)'],
    ['170 gm bottle(s)'],
    ['170 gm canister(s)'],
    ['170 gm jar(s)'],
    ['170 gm tube(s)'],
    ['170 mL bag(s)'],
    ['170 mL bottle(s)'],
    ['170 mL drop btl(s)'],
    ['170.1 gm tube(s)'],
    ['170.3 gm bottle(s)'],
    ['1700 gm bottle(s)'],
    ['174 gm jar(s)'],
    ['174 mL packet(s)'],
    ['175 gm tube(s)'],
    ['175 mL bottle(s)'],
    ['176 gm bottle(s)'],
    ['177 gm bottle(s)'],
    ['177 mL aer w/adap(s)'],
    ['177 mL bottle(s)'],
    ['177 mL can(s)'],
    ['177 mL canister(s)'],
    ['177 mL kit(s)'],
    ['177 mL squeez btl(s)'],
    ['177.4 mL bottle(s)'],
    ['178 mL bottle(s)'],
    ['178 mL box(s)'],
    ['18 gm canister(s)'],
    ['18 gm jar(s)'],
    ['18 gm tube(s)'],
    ['18 mL drop btl(s)'],
    ['18 mL vial(s)'],
    ['18.2 mL aer w/adap(s)'],
    ['18.77 gm bottle(s)'],
    ['180 gm bottle(s)'],
    ['180 gm tube(s)'],
    ['180 mL bag(s)'],
    ['180 mL bottle(s)'],
    ['180 mL tube(s)'],
    ['1810 gm bag(s)'],
    ['1810 gm packet(s)'],
    ['1814 gm bottle(s)'],
    ['183 gm bottle(s)'],
    ['184 gm aer w/adap(s)'],
    ['184 gm bottle(s)'],
    ['184 gm jar(s)'],
    ['184 gm squeez btl(s)'],
    ['187 gm bottle(s)'],
    ['1892 mL bottle(s)'],
    ['190 mL bag(s)'],
    ['1900 mL bottle(s)'],
    ['19000 mL bottle(s)'],
    ['192 gm jar(s)'],
    ['192 mL bottle(s)'],
    ['192 mL box(s)'],
    ['1920 mL bag(s)'],
    ['1920 mL bottle(s)'],
    ['198 gm bottle(s)'],
    ['198 gm packet(s)'],
    ['198 gm tube(s)'],
    ['198.4 gm bottle(s)'],
    ['2 gm blist pack(s)'],
    ['2 gm bottle(s)'],
    ['2 gm jar(s)'],
    ['2 gm packet(s)'],
    ['2 gm tube(s)'],
    ['2 mL ampul(s)'],
    ['2 mL ampul/kit(s)'],
    ['2 mL blist pack(s)'],
    ['2 mL cartridge(s)'],
    ['2 mL drop btl(s)'],
    ['2 mL syringe(s)'],
    ['2 mL tube(s)'],
    ['2 mL vial(s)'],
    ['2.2 mL vial(s)'],
    ['2.25 mL syringe(s)'],
    ['2.3 mL vial(s)'],
    ['2.4 mL box(s)'],
    ['2.4 mL cartridge(s)'],
    ['2.4 mL syringe(s)'],
    ['2.4 mL vial(s)'],
    ['2.48 mL syringe(s)'],
    ['2.5 gm blist pack(s)'],
    ['2.5 gm packet(s)'],
    ['2.5 mL ampul(s)'],
    ['2.5 mL bottle(s)'],
    ['2.5 mL cup(s)'],
    ['2.5 mL drop btl(s)'],
    ['2.5 mL squeez btl(s)'],
    ['2.5 mL syringe(s)'],
    ['2.5 mL vial(s)'],
    ['2.55 gm pf appli(s)'],
    ['2.625 mL syringe(s)'],
    ['2.7 mL syringe(s)'],
    ['2.8 mL drop btl(s)'],
    ['2.8 mL vial(s)'],
    ['20 gm bottle(s)'],
    ['20 gm jar(s)'],
    ['20 gm tube(s)'],
    ['20 gm tube/kit(s)'],
    ['20 mL ampul(s)'],
    ['20 mL bottle(s)'],
    ['20 mL cup(s)'],
    ['20 mL drop btl(s)'],
    ['20 mL syringe(s)'],
    ['20 mL tube(s)'],
    ['20 mL vial(s)'],
    ['20.04 gm bottle(s)'],
    ['20.3 mL cup(s)'],
    ['200 gm can(s)'],
    ['200 gm canister(s)'],
    ['200 gm jar(s)'],
    ['200 gm tube(s)'],
    ['200 mL bag(s)'],
    ['200 mL bottle(s)'],
    ['200 mL box(s)'],
    ['200 mL flex cont(s)'],
    ['200 mL glass cont(s)'],
    ['200 mL tube(s)'],
    ['200 mL vial(s)'],
    ['2000 mL bag(s)'],
    ['2000 mL bottle(s)'],
    ['2000 mL flex cont(s)'],
    ['20000 mL bottle(s)'],
    ['201 mL bottle(s)'],
    ['201.6 gm can(s)'],
    ['204 gm bottle(s)'],
    ['204 gm can(s)'],
    ['205 gm canister(s)'],
    ['2053 mL bag(s)'],
    ['207 gm tube(s)'],
    ['207 mL bottle(s)'],
    ['208 gm box(s)'],
    ['21 gm box(s)'],
    ['21 gm tube(s)'],
    ['21 gm tube/kit(s)'],
    ['21.1 mL vial(s)'],
    ['21.22 gm jar(s)'],
    ['21.25 gm tube(s)'],
    ['210 gm bottle(s)'],
    ['210 gm can(s)'],
    ['210 mL bottle(s)'],
    ['210 mL can(s)'],
    ['210 mL canister(s)'],
    ['210 mL vial(s)'],
    ['212 gm jar(s)'],
    ['216 mL tube(s)'],
    ['219.7 gm tube(s)'],
    ['22 gm tube(s)'],
    ['22 mL bottle(s)'],
    ['22 mL squeez btl(s)'],
    ['22 mL tube(s)'],
    ['22.2 mL vial(s)'],
    ['22.5 gm bottle(s)'],
    ['22.5 mL bottle(s)'],
    ['22.5 mL packet(s)'],
    ['220 gm canister(s)'],
    ['220 mL bag(s)'],
    ['220 mL bottle(s)'],
    ['222 mL bottle(s)'],
    ['224 gm tube(s)'],
    ['225 gm bottle(s)'],
    ['225 gm jar(s)'],
    ['225 mL bottle(s)'],
    ['226 gm bottle(s)'],
    ['226 gm jar(s)'],
    ['226 gm tube(s)'],
    ['226.8 gm bottle(s)'],
    ['226.8 gm jar(s)'],
    ['226.8 gm kit(s)'],
    ['227 gm bag(s)'],
    ['227 gm bottle(s)'],
    ['227 gm can(s)'],
    ['227 gm canister(s)'],
    ['227 gm jar(s)'],
    ['227 gm tube(s)'],
    ['227.2 gm jar(s)'],
    ['2270 gm jar(s)'],
    ['228 gm bottle(s)'],
    ['228 gm jar(s)'],
    ['23 gm squeez btl(s)'],
    ['23.3 gm jar(s)'],
    ['23.5 mL vial(s)'],
    ['230 gm bottle(s)'],
    ['230 mL bottle(s)'],
    ['230 mL squeez btl(s)'],
    ['230 mL tube(s)'],
    ['231 gm jar(s)'],
    ['235 gm bottle(s)'],
    ['235 gm jar(s)'],
    ['236 gm bottle(s)'],
    ['236 gm canister(s)'],
    ['236 mL bottle(s)'],
    ['236 mL jar(s)'],
    ['236 mL squeez btl(s)'],
    ['236.5 mL bottle(s)'],
    ['236.56 mL bottle(s)'],
    ['237 gm bottle(s)'],
    ['237 mL bottle(s)'],
    ['237 mL box(s)'],
    ['237 mL can(s)'],
    ['237 mL flex cont(s)'],
    ['237 mL packet(s)'],
    ['237 mL squeez btl(s)'],
    ['237 mL tube(s)'],
    ['238 gm bottle(s)'],
    ['238 gm jar(s)'],
    ['238.75 mL bag(s)'],
    ['239 mL kit(s)'],
    ['239.4 gm jar(s)'],
    ['24 gm box(s)'],
    ['24 gm kit(s)'],
    ['24 gm tube(s)'],
    ['24 mL vial(s)'],
    ['24.81 gm tube(s)'],
    ['240 gm jar(s)'],
    ['240 gm tube(s)'],
    ['240 mL bottle(s)'],
    ['240 mL jar(s)'],
    ['240 mL squeez btl(s)'],
    ['240 mL tube(s)'],
    ['2400 gm jar(s)'],
    ['2400 mL bag(s)'],
    ['245 mL bottle(s)'],
    ['245.5 mL bottle(s)'],
    ['248 gm bottle(s)'],
    ['248 gm canister(s)'],
    ['25 gm aer w/adap(s)'],
    ['25 gm bottle(s)'],
    ['25 gm jar(s)'],
    ['25 gm tube(s)'],
    ['25 gm tube/kit(s)'],
    ['25 mL bag(s)'],
    ['25 mL bottle(s)'],
    ['25 mL cup(s)'],
    ['25 mL flex cont(s)'],
    ['25 mL squeez btl(s)'],
    ['25 mL syringe(s)'],
    ['25 mL vial(s)'],
    ['250 gm bottle(s)'],
    ['250 gm tube(s)'],
    ['250 mL bag(s)'],
    ['250 mL bottle(s)'],
    ['250 mL box(s)'],
    ['250 mL can(s)'],
    ['250 mL flex cont(s)'],
    ['250 mL glass cont(s)'],
    ['250 mL jar(s)'],
    ['250 mL packet(s)'],
    ['250 mL vial(s)'],
    ['2500 gm jar(s)'],
    ['2500 mL bag(s)'],
    ['2500 mL flex cont(s)'],
    ['251 mL bottle(s)'],
    ['255 gm aer w/adap(s)'],
    ['255 gm squeez btl(s)'],
    ['255 gm tube(s)'],
    ['255 mL bottle(s)'],
    ['2566 mL bag(s)'],
    ['26 gm bottle(s)'],
    ['26 gm packet(s)'],
    ['26 gm tube(s)'],
    ['26 mL bottle(s)'],
    ['26 mL squeez btl(s)'],
    ['26 mL vial(s)'],
    ['26.25 mL vial(s)'],
    ['26.3 mL vial(s)'],
    ['265.6 mL kit(s)'],
    ['266 mL bottle(s)'],
    ['266 mL squeez btl(s)'],
    ['267 gm bag(s)'],
    ['267 gm packet(s)'],
    ['270 gm tube(s)'],
    ['270 mL bottle(s)'],
    ['2720 gm bottle(s)'],
    ['2720 gm box(s)'],
    ['2720 gm packet(s)'],
    ['274 mL bottle(s)'],
    ['274 mL box(s)'],
    ['275 gm bottle(s)'],
    ['275 gm can(s)'],
    ['275 gm tube(s)'],
    ['276 gm bag(s)'],
    ['28 gm bottle(s)'],
    ['28 gm jar(s)'],
    ['28 gm tube(s)'],
    ['28 mL bottle(s)'],
    ['28 mL squeez btl(s)'],
    ['28.3 gm tube(s)'],
    ['28.33 gm bottle(s)'],
    ['28.33 gm tube(s)'],
    ['28.35 gm bottle(s)'],
    ['28.35 gm tube(s)'],
    ['28.4 gm bottle(s)'],
    ['28.4 gm kit(s)'],
    ['28.4 gm tube(s)'],
    ['28.4 gm tube/kit(s)'],
    ['28.5 gm can(s)'],
    ['28.5 gm canister(s)'],
    ['28.5 gm tube(s)'],
    ['28.5 mL bottle(s)'],
    ['283 gm bottle(s)'],
    ['283 gm jar(s)'],
    ['283.5 gm bottle(s)'],
    ['283.52 gm tube(s)'],
    ['284 gm bottle(s)'],
    ['285 gm bottle(s)'],
    ['285 gm jar(s)'],
    ['289 gm bottle(s)'],
    ['29 gm tube(s)'],
    ['29.5 mL bottle(s)'],
    ['29.5 mL tube(s)'],
    ['29.57 mL bottle(s)'],
    ['29.57 mL drop btl(s)'],
    ['29.6 mL bottle(s)'],
    ['29.6 mL drop btl(s)'],
    ['29.6 mL squeez btl(s)'],
    ['295 mL box(s)'],
    ['296 mL bottle(s)'],
    ['296.2 mL kit(s)'],
    ['3 gm blist pack(s)'],
    ['3 gm packet(s)'],
    ['3 gm pf appli(s)'],
    ['3 gm tube(s)'],
    ['3 mL ampul(s)'],
    ['3 mL cartridge(s)'],
    ['3 mL drop btl(s)'],
    ['3 mL pf appli(s)'],
    ['3 mL syringe(s)'],
    ['3 mL vial(s)'],
    ['3.2 mL syringe(s)'],
    ['3.5 gm packet(s)'],
    ['3.5 gm tube(s)'],
    ['3.5 mL bottle(s)'],
    ['3.5 mL cartridge(s)'],
    ['3.5 mL drop btl(s)'],
    ['3.5 mL syringe(s)'],
    ['3.7 mL squeez btl(s)'],
    ['3.8 gm aer w/adap(s)'],
    ['3.8 mL vial(s)'],
    ['3.9 mL syringe(s)'],
    ['30 gm bottle(s)'],
    ['30 gm box(s)'],
    ['30 gm can(s)'],
    ['30 gm canister(s)'],
    ['30 gm jar(s)'],
    ['30 gm squeez btl(s)'],
    ['30 gm tube(s)'],
    ['30 gm tube/kit(s)'],
    ['30 mL ampul(s)'],
    ['30 mL blist pack(s)'],
    ['30 mL bottle(s)'],
    ['30 mL box(s)'],
    ['30 mL canister(s)'],
    ['30 mL cartridge(s)'],
    ['30 mL cup(s)'],
    ['30 mL drop btl(s)'],
    ['30 mL packet(s)'],
    ['30 mL squeez btl(s)'],
    ['30 mL syringe(s)'],
    ['30 mL tube(s)'],
    ['30 mL vial(s)'],
    ['30.5 gm bottle(s)'],
    ['300 gm bottle(s)'],
    ['300 gm can(s)'],
    ['300 gm jar(s)'],
    ['300 mL bag(s)'],
    ['300 mL bottle(s)'],
    ['300 mL packet(s)'],
    ['300 mL vial(s)'],
    ['3000 mL bag(s)'],
    ['3000 mL bottle(s)'],
    ['3000 mL flex cont(s)'],
    ['31 gm tube(s)'],
    ['311 gm aer w/adap(s)'],
    ['311 gm bottle(s)'],
    ['313 gm tube(s)'],
    ['315 gm kit(s)'],
    ['315 mL bottle(s)'],
    ['315 mL vial(s)'],
    ['3178 gm jar(s)'],
    ['32 mL packet(s)'],
    ['32.5 mL syringe(s)'],
    ['320 mL bottle(s)'],
    ['324.86 mL box(s)'],
    ['325 gm kit(s)'],
    ['325 mL bottle(s)'],
    ['33 gm packet(s)'],
    ['33.4 gm canister(s)'],
    ['330 mL bottle(s)'],
    ['330 mL box(s)'],
    ['331 gm jar(s)'],
    ['332 mL bottle(s)'],
    ['335 mL bottle(s)'],
    ['336 gm can(s)'],
    ['34 mL vial(s)'],
    ['34.6 mL kit(s)'],
    ['340 gm bottle(s)'],
    ['340 gm jar(s)'],
    ['340 gm tube(s)'],
    ['340 mL bottle(s)'],
    ['340.2 gm bottle(s)'],
    ['340.2 gm jar(s)'],
    ['341 gm bag(s)'],
    ['343 gm can(s)'],
    ['348.6 gm can(s)'],
    ['35 gm bottle(s)'],
    ['35 gm box(s)'],
    ['35 gm jar(s)'],
    ['35 gm tube(s)'],
    ['35 mL bottle(s)'],
    ['35 mL canister(s)'],
    ['35.4 gm jar(s)'],
    ['35.4 gm tube(s)'],
    ['35.44 gm tube(s)'],
    ['35.5 mL bottle(s)'],
    ['350 gm bottle(s)'],
    ['350 gm can(s)'],
    ['350 gm tube(s)'],
    ['350 mL bag(s)'],
    ['350 mL bottle(s)'],
    ['351 gm can(s)'],
    ['352 gm can(s)'],
    ['354 gm can(s)'],
    ['354 mL bottle(s)'],
    ['354 mL kit(s)'],
    ['354.8 mL bottle(s)'],
    ['355 gm kit(s)'],
    ['355 mL bottle(s)'],
    ['357 gm can(s)'],
    ['36 gm packet(s)'],
    ['36 gm tube(s)'],
    ['360 gm can(s)'],
    ['360 gm canister(s)'],
    ['360 gm jar(s)'],
    ['360 mL bottle(s)'],
    ['363 gm can(s)'],
    ['3630 gm bottle(s)'],
    ['366 gm can(s)'],
    ['368 gm bottle(s)'],
    ['368 gm jar(s)'],
    ['368.5 gm jar(s)'],
    ['368.76 gm jar(s)'],
    ['369 gm bottle(s)'],
    ['369 gm jar(s)'],
    ['37 mL squeez btl(s)'],
    ['37.5 gm packet(s)'],
    ['37.5 gm tube(s)'],
    ['37.5 mL bottle(s)'],
    ['371 gm can(s)'],
    ['375 gm bottle(s)'],
    ['375 gm kit(s)'],
    ['378 gm can(s)'],
    ['378 gm jar(s)'],
    ['3780 mL bottle(s)'],
    ['3780 mL box(s)'],
    ['3785 mL bottle(s)'],
    ['3785.41 mL bottle(s)'],
    ['3790 mL bottle(s)'],
    ['38 gm tube(s)'],
    ['3800 mL bottle(s)'],
    ['3800 mL box(s)'],
    ['384 mL can(s)'],
    ['3840 gm jar(s)'],
    ['3840 mL bottle(s)'],
    ['3840 mL box(s)'],
    ['3840 mL jar(s)'],
    ['385 gm bottle(s)'],
    ['385 gm jar(s)'],
    ['386 gm can(s)'],
    ['387 mL box(s)'],
    ['387 mL kit(s)'],
    ['390 mL bottle(s)'],
    ['3900 mL packet(s)'],
    ['396 gm bottle(s)'],
    ['396 gm jar(s)'],
    ['396 gm packet(s)'],
    ['396 gm tube(s)'],
    ['397 gm can(s)'],
    ['397 gm jar(s)'],
    ['397 gm kit(s)'],
    ['399 gm bag(s)'],
    ['399 mL squeez btl(s)'],
    ['4 gm aer w/adap(s)'],
    ['4 gm blist pack(s)'],
    ['4 gm jar(s)'],
    ['4 gm packet(s)'],
    ['4 gm tube(s)'],
    ['4 mL ampul(s)'],
    ['4 mL bottle(s)'],
    ['4 mL box(s)'],
    ['4 mL cartridge(s)'],
    ['4 mL cup(s)'],
    ['4 mL drop btl(s)'],
    ['4 mL kit(s)'],
    ['4 mL packet(s)'],
    ['4 mL squeez btl(s)'],
    ['4 mL syringe(s)'],
    ['4 mL tube stick(s)'],
    ['4 mL tube(s)'],
    ['4 mL vial(s)'],
    ['4.1 gm bottle(s)'],
    ['4.2 mL bottle(s)'],
    ['4.2 mL syringe(s)'],
    ['4.4 mL vial(s)'],
    ['4.5 mL aer w/adap(s)'],
    ['4.6 gm pf appli(s)'],
    ['4.8 mL bottle(s)'],
    ['4.9 gm bottle(s)'],
    ['4.99 gm jar(s)'],
    ['40 gm jar(s)'],
    ['40 gm tube(s)'],
    ['40 gm tube/kit(s)'],
    ['40 mL bottle(s)'],
    ['40 mL syringe(s)'],
    ['40 mL tube(s)'],
    ['40 mL vial(s)'],
    ['400 gm bottle(s)'],
    ['400 gm can(s)'],
    ['400 gm canister(s)'],
    ['400 gm jar(s)'],
    ['400 gm packet(s)'],
    ['400 mL bag(s)'],
    ['400 mL bottle(s)'],
    ['400 mL vial(s)'],
    ['4000 mL bag(s)'],
    ['4000 mL bottle(s)'],
    ['405 gm bottle(s)'],
    ['410 gm can(s)'],
    ['414 mL bottle(s)'],
    ['415 mL bag(s)'],
    ['418 gm jar(s)'],
    ['418 gm tube(s)'],
    ['42 gm bottle(s)'],
    ['42 gm jar(s)'],
    ['42 gm tube(s)'],
    ['42.5 gm pf appli(s)'],
    ['42.5 gm tube stick(s)'],
    ['42.5 gm tube(s)'],
    ['42.52 gm jar(s)'],
    ['420 gm can(s)'],
    ['420 gm jar(s)'],
    ['420 mL bottle(s)'],
    ['424.96 gm jar(s)'],
    ['425 gm jar(s)'],
    ['425 gm packet(s)'],
    ['425 gm tube(s)'],
    ['426 gm bottle(s)'],
    ['426 gm jar(s)'],
    ['43 gm bottle(s)'],
    ['43 gm jar(s)'],
    ['43 gm tube(s)'],
    ['430 gm jar(s)'],
    ['437 mL bottle(s)'],
    ['44 gm bottle(s)'],
    ['44 gm kit(s)'],
    ['44 mL bottle(s)'],
    ['44 mL cup(s)'],
    ['44 mL squeez btl(s)'],
    ['44 mL tube(s)'],
    ['44.3 mL bottle(s)'],
    ['44.4 mL tube(s)'],
    ['443 mL bottle(s)'],
    ['444 mL bottle(s)'],
    ['45 gm bottle(s)'],
    ['45 gm jar(s)'],
    ['45 gm tube(s)'],
    ['45 gm tube/kit(s)'],
    ['45 mL bottle(s)'],
    ['45 mL box(s)'],
    ['45 mL packet(s)'],
    ['45 mL squeez btl(s)'],
    ['45 mL tube(s)'],
    ['45 mL vial(s)'],
    ['450 gm bottle(s)'],
    ['450 gm jar(s)'],
    ['450 gm tube(s)'],
    ['450 mL bottle(s)'],
    ['452 gm jar(s)'],
    ['453 gm bottle(s)'],
    ['453 gm jar(s)'],
    ['453.5 gm jar(s)'],
    ['453.6 gm bottle(s)'],
    ['453.6 gm jar(s)'],
    ['454 gm bag(s)'],
    ['454 gm bottle(s)'],
    ['454 gm box(s)'],
    ['454 gm can(s)'],
    ['454 gm jar(s)'],
    ['454 gm tube(s)'],
    ['459 gm jar(s)'],
    ['46 gm tube(s)'],
    ['46.4 gm bottle(s)'],
    ['46.6 gm jar(s)'],
    ['460 mL bottle(s)'],
    ['462 gm jar(s)'],
    ['464 gm jar(s)'],
    ['464 mL bottle(s)'],
    ['468 gm jar(s)'],
    ['47 gm tube(s)'],
    ['470 mL bottle(s)'],
    ['472 mL bottle(s)'],
    ['473 mL bottle(s)'],
    ['473 mL box(s)'],
    ['473.18 mL bottle(s)'],
    ['474 mL bottle(s)'],
    ['475 gm canister(s)'],
    ['475 mL bottle(s)'],
    ['477 gm jar(s)'],
    ['477.5 mL bag(s)'],
    ['479 gm jar(s)'],
    ['48 gm jar(s)'],
    ['48 gm tube(s)'],
    ['48 mL bottle(s)'],
    ['48 mL canister(s)'],
    ['48 mL vial(s)'],
    ['480 gm bottle(s)'],
    ['480 gm canister(s)'],
    ['480 gm jar(s)'],
    ['480 mL bottle(s)'],
    ['480 mL jar(s)'],
    ['484.5 gm jar(s)'],
    ['488 mL bottle(s)'],
    ['49 gm jar(s)'],
    ['49 gm pf appli(s)'],
    ['49 gm tube(s)'],
    ['49.6 gm tube(s)'],
    ['491 mL bottle(s)'],
    ['5 gm blist pack(s)'],
    ['5 gm bottle(s)'],
    ['5 gm box(s)'],
    ['5 gm drop btl(s)'],
    ['5 gm jar(s)'],
    ['5 gm packet(s)'],
    ['5 gm pf appli(s)'],
    ['5 gm tube(s)'],
    ['5 mL aer w/adap(s)'],
    ['5 mL amp w/dev(s)'],
    ['5 mL ampul(s)'],
    ['5 mL blist pack(s)'],
    ['5 mL bottle(s)'],
    ['5 mL cup(s)'],
    ['5 mL dose-pack(s)'],
    ['5 mL drop btl(s)'],
    ['5 mL packet(s)'],
    ['5 mL syringe(s)'],
    ['5 mL tube(s)'],
    ['5 mL vial(s)'],
    ['5.1 gm tube(s)'],
    ['5.25 gm tube(s)'],
    ['5.26 mL vial(s)'],
    ['5.5 mL drop btl(s)'],
    ['5.5 mL vial(s)'],
    ['5.7 mL vial(s)'],
    ['5.9 gm aer w/adap(s)'],
    ['5.9 gm canister(s)'],
    ['5.9 mL aer w/adap(s)'],
    ['50 gm bottle(s)'],
    ['50 gm box(s)'],
    ['50 gm can(s)'],
    ['50 gm canister(s)'],
    ['50 gm jar(s)'],
    ['50 gm tube(s)'],
    ['50 mL bag(s)'],
    ['50 mL bottle(s)'],
    ['50 mL box(s)'],
    ['50 mL drop btl(s)'],
    ['50 mL flex cont(s)'],
    ['50 mL glass cont(s)'],
    ['50 mL squeez btl(s)'],
    ['50 mL syringe(s)'],
    ['50 mL vial(s)'],
    ['500 gm bottle(s)'],
    ['500 gm can(s)'],
    ['500 gm canister(s)'],
    ['500 gm jar(s)'],
    ['500 mL bag(s)'],
    ['500 mL bottle(s)'],
    ['500 mL drop btl(s)'],
    ['500 mL flex cont(s)'],
    ['500 mL glass cont(s)'],
    ['500 mL squeez btl(s)'],
    ['500 mL vial(s)'],
    ['5000 mL bag(s)'],
    ['5000 mL bottle(s)'],
    ['5000 mL flex cont(s)'],
    ['502 gm canister(s)'],
    ['503 mL bag(s)'],
    ['504.8 mL bag(s)'],
    ['507 gm bottle(s)'],
    ['51 gm jar(s)'],
    ['51 gm tube(s)'],
    ['510 gm bottle(s)'],
    ['510 gm jar(s)'],
    ['52 gm tube(s)'],
    ['52 mL bottle(s)'],
    ['52 mL drop btl(s)'],
    ['52.5 mL vial(s)'],
    ['52.6 mL vial(s)'],
    ['520 gm can(s)'],
    ['522.8 mL bag(s)'],
    ['53.6 gm pf appli(s)'],
    ['532 mL bottle(s)'],
    ['537 gm jar(s)'],
    ['538 gm bottle(s)'],
    ['538 gm jar(s)'],
    ['539 gm box(s)'],
    ['54 gm bottle(s)'],
    ['54 gm tube/kit(s)'],
    ['54 mL bag(s)'],
    ['54 mL bottle(s)'],
    ['54.5 mL bottle(s)'],
    ['542 mL bag(s)'],
    ['544 gm kit(s)'],
    ['545 mL flex cont(s)'],
    ['549 gm can(s)'],
    ['55 gm bottle(s)'],
    ['55 mL syringe(s)'],
    ['553 gm can(s)'],
    ['554 gm kit(s)'],
    ['56 gm bottle(s)'],
    ['56 gm canister(s)'],
    ['56 gm jar(s)'],
    ['56 gm tube(s)'],
    ['56 mL tube(s)'],
    ['56.3 gm pf appli(s)'],
    ['56.5 gm tube(s)'],
    ['56.6 gm jar(s)'],
    ['56.6 gm tube(s)'],
    ['56.7 gm bottle(s)'],
    ['56.7 gm jar(s)'],
    ['56.7 gm tube(s)'],
    ['56.7 mL bottle(s)'],
    ['56.8 gm tube(s)'],
    ['561 gm can(s)'],
    ['566 gm can(s)'],
    ['567 gm can(s)'],
    ['568 gm can(s)'],
    ['57 gm bottle(s)'],
    ['57 gm can(s)'],
    ['57 gm canister(s)'],
    ['57 gm jar(s)'],
    ['57 gm squeez btl(s)'],
    ['57 gm tube(s)'],
    ['57 mL bottle(s)'],
    ['570 gm can(s)'],
    ['570 mL bottle(s)'],
    ['575 gm jar(s)'],
    ['576 gm jar(s)'],
    ['578 gm can(s)'],
    ['581 gm can(s)'],
    ['584 gm can(s)'],
    ['587 gm can(s)'],
    ['59 mL bottle(s)'],
    ['59 mL box(s)'],
    ['59 mL can(s)'],
    ['59 mL canister(s)'],
    ['59 mL drop btl(s)'],
    ['59 mL jar(s)'],
    ['59 mL squeez btl(s)'],
    ['59 mL tube(s)'],
    ['59.1 mL bottle(s)'],
    ['59.14 mL bottle(s)'],
    ['59.15 mL tube(s)'],
    ['59.2 mL bottle(s)'],
    ['593 gm can(s)'],
    ['595 gm bottle(s)'],
    ['6 gm aer w/adap(s)'],
    ['6 gm tube(s)'],
    ['6 mL bottle(s)'],
    ['6 mL cup(s)'],
    ['6 mL drop btl(s)'],
    ['6 mL syringe(s)'],
    ['6 mL vial(s)'],
    ['6.1 gm aer w/adap(s)'],
    ['6.1 gm canister(s)'],
    ['6.26 gm bottle(s)'],
    ['6.5 gm tube(s)'],
    ['6.6 mL bottle(s)'],
    ['6.67 mL cup(s)'],
    ['6.7 gm canister(s)'],
    ['6.7 gm pf appli(s)'],
    ['6.7 mL bottle(s)'],
    ['6.8 gm canister(s)'],
    ['6.8 mL cup(s)'],
    ['6.9 gm aer w/adap(s)'],
    ['60 gm bottle(s)'],
    ['60 gm can(s)'],
    ['60 gm canister(s)'],
    ['60 gm jar(s)'],
    ['60 gm squeez btl(s)'],
    ['60 gm tube(s)'],
    ['60 gm tube/kit(s)'],
    ['60 mL bag(s)'],
    ['60 mL bottle(s)'],
    ['60 mL can(s)'],
    ['60 mL drop btl(s)'],
    ['60 mL squeez btl(s)'],
    ['60 mL syringe(s)'],
    ['60 mL tube(s)'],
    ['60 mL vial(s)'],
    ['600 mL bottle(s)'],
    ['6000 mL flex cont(s)'],
    ['610 gm can(s)'],
    ['610 gm canister(s)'],
    ['610 gm jar(s)'],
    ['62.1 mL bottle(s)'],
    ['62.5 mL bottle(s)'],
    ['62.5 mL box(s)'],
    ['621 mL bottle(s)'],
    ['624 gm can(s)'],
    ['629 gm can(s)'],
    ['629 gm jar(s)'],
    ['63 gm canister(s)'],
    ['638 gm can(s)'],
    ['646 gm can(s)'],
    ['65 mL bag(s)'],
    ['65 mL vial(s)'],
    ['652 gm can(s)'],
    ['658 gm can(s)'],
    ['658 gm jar(s)'],
    ['66 gm tube(s)'],
    ['66 mL bottle(s)'],
    ['66 mL squeez btl(s)'],
    ['660 gm canister(s)'],
    ['660 gm jar(s)'],
    ['661 gm can(s)'],
    ['662 gm jar(s)'],
    ['67.5 mL squeez btl(s)'],
    ['679 gm jar(s)'],
    ['68 gm bottle(s)'],
    ['68 mL can(s)'],
    ['680 gm can(s)'],
    ['694 gm can(s)'],
    ['697.4 gm jar(s)'],
    ['7 gm can(s)'],
    ['7 gm kit(s)'],
    ['7 gm tube(s)'],
    ['7 mL bottle(s)'],
    ['7 mL syringe(s)'],
    ['7 mL vial(s)'],
    ['7.1 gm tube(s)'],
    ['7.32 gm bottle(s)'],
    ['7.4 mL tube(s)'],
    ['7.5 gm bottle(s)'],
    ['7.5 gm jar(s)'],
    ['7.5 mL cup(s)'],
    ['7.5 mL drop btl(s)'],
    ['7.5 mL packet(s)'],
    ['7.5 mL syringe(s)'],
    ['7.5 mL tube(s)'],
    ['7.5 mL vial(s)'],
    ['7.52 gm bottle(s)'],
    ['7.7 mL aer w/adap(s)'],
    ['7.7 mL bottle(s)'],
    ['70 gm can(s)'],
    ['70 gm canister(s)'],
    ['70 gm jar(s)'],
    ['70 gm tube(s)'],
    ['70 mL bag(s)'],
    ['70 mL bottle(s)'],
    ['70.8 gm jar(s)'],
    ['70.8 gm tube(s)'],
    ['700 gm can(s)'],
    ['700 mL bottle(s)'],
    ['708 mL bottle(s)'],
    ['71 gm aer w/adap(s)'],
    ['71 gm bottle(s)'],
    ['71 gm jar(s)'],
    ['71 gm pf appli(s)'],
    ['71 gm tube(s)'],
    ['710 mL bottle(s)'],
    ['72 mL tube(s)'],
    ['720 mL bottle(s)'],
    ['73 mL bottle(s)'],
    ['73 mL roll(s)'],
    ['74 mL bottle(s)'],
    ['745 mL flex cont(s)'],
    ['75 gm bottle(s)'],
    ['75 gm jar(s)'],
    ['75 mL aer w/adap(s)'],
    ['75 mL bottle(s)'],
    ['75 mL jar(s)'],
    ['75 mL syringe(s)'],
    ['75 mL tube(s)'],
    ['75 mL vial(s)'],
    ['750 gm bag(s)'],
    ['750 gm can(s)'],
    ['750 mL bag(s)'],
    ['750 mL bottle(s)'],
    ['76 gm canister(s)'],
    ['76.5 gm bottle(s)'],
    ['76.5 gm tube(s)'],
    ['765 gm bottle(s)'],
    ['769 mL bottle(s)'],
    ['771 gm can(s)'],
    ['78 gm bottle(s)'],
    ['78 gm canister(s)'],
    ['78 gm tube(s)'],
    ['79.98 gm bottle(s)'],
    ['798 gm jar(s)'],
    ['798 mL squeez btl(s)'],
    ['8 gm bottle(s)'],
    ['8 gm canister(s)'],
    ['8 gm jar(s)'],
    ['8 gm pf appli(s)'],
    ['8 mL bottle(s)'],
    ['8 mL drop btl(s)'],
    ['8 mL packet(s)'],
    ['8 mL squeez btl(s)'],
    ['8 mL syringe(s)'],
    ['8 mL vial(s)'],
    ['8.1 mL bottle(s)'],
    ['8.3 mL drop btl(s)'],
    ['8.4 mL vial(s)'],
    ['8.43 mL aer w/adap(s)'],
    ['8.5 gm bottle(s)'],
    ['8.5 gm canister(s)'],
    ['8.5 mL drop btl(s)'],
    ['8.5 mL vial(s)'],
    ['8.71 gm bottle(s)'],
    ['8.8 gm aer w/adap(s)'],
    ['80 gm jar(s)'],
    ['80 gm tube(s)'],
    ['80 mL bottle(s)'],
    ['80 mL tube(s)'],
    ['800 gm can(s)'],
    ['800 mL bag(s)'],
    ['800 mL bottle(s)'],
    ['81 gm bottle(s)'],
    ['81.2 mL amp w/dev(s)'],
    ['810 mL bag(s)'],
    ['822 gm jar(s)'],
    ['833 gm can(s)'],
    ['845 gm can(s)'],
    ['85 gm bottle(s)'],
    ['85 gm box(s)'],
    ['85 gm canister(s)'],
    ['85 gm jar(s)'],
    ['85 gm kit(s)'],
    ['85 gm tube(s)'],
    ['85 mL bottle(s)'],
    ['85.05 gm bottle(s)'],
    ['85.05 gm tube(s)'],
    ['85.1 gm jar(s)'],
    ['850 gm bottle(s)'],
    ['850 gm jar(s)'],
    ['86 gm tube(s)'],
    ['861 gm jar(s)'],
    ['862 gm packet(s)'],
    ['87 mL packet(s)'],
    ['873 gm can(s)'],
    ['88 mL bottle(s)'],
    ['88 mL squeez btl(s)'],
    ['88.7 mL bottle(s)'],
    ['88.72 mL tube(s)'],
    ['887 mL bottle(s)'],
    ['89 mL bottle(s)'],
    ['89 mL can(s)'],
    ['89 mL squeez btl(s)'],
    ['89 mL tube(s)'],
    ['890 gm packet(s)'],
    ['9 gm tube(s)'],
    ['9 mL bottle(s)'],
    ['9 mL drop btl(s)'],
    ['9 mL tube(s)'],
    ['9 mL vial(s)'],
    ['9.1 mL aer w/adap(s)'],
    ['9.12 mL bottle(s)'],
    ['9.2 mL drop btl(s)'],
    ['9.35 gm tube(s)'],
    ['9.4 gm tube(s)'],
    ['9.8 mL aer w/adap(s)'],
    ['9.8 mL bottle(s)'],
    ['9.9 mL aer w/adap(s)'],
    ['9.98 gm bottle(s)'],
    ['90 gm bottle(s)'],
    ['90 gm jar(s)'],
    ['90 gm tube(s)'],
    ['90 mL bottle(s)'],
    ['90 mL tube(s)'],
    ['900 gm can(s)'],
    ['907 gm can(s)'],
    ['907 gm jar(s)'],
    ['907.2 gm bottle(s)'],
    ['913 gm box(s)'],
    ['913 gm can(s)'],
    ['917 gm can(s)'],
    ['92 gm bottle(s)'],
    ['92 gm tube(s)'],
    ['92.5 mL vial(s)'],
    ['941 gm box(s)'],
    ['941 gm packet(s)'],
    ['946 mL bottle(s)'],
    ['946 mL box(s)'],
    ['946 mL can(s)'],
    ['948 mL bottle(s)'],
    ['96 gm bottle(s)'],
    ['96 gm tube(s)'],
    ['96 mL bottle(s)'],
    ['960 mL bottle(s)'],
    ['964 gm can(s)'],
    ['975 gm jar(s)'],
    ['976 mL bottle(s)'],
    ['98 mL bottle(s)'],
    ['99 gm bottle(s)'],
    ['99 gm jar(s)'],
    ['99 gm tube(s)'],
    ['99.2 gm jar(s)'],
    ['993.6 mL packet(s)'],
    ['L'],
    ['aer br.act(s) of 1'],
    ['aer ref(s) of 1'],
    ['aer w/adap(s) of 1'],
    ['aer w/adap(s) of 2'],
    ['aer w/adap(s) of 6'],
    ['ampul(s) of 1'],
    ['ampul(s) of 10'],
    ['ampul(s) of 144'],
    ['application(s)'],
    ['applicator(s)ful'],
    ['bag(s) of 1'],
    ['bag(s) of 100'],
    ['bag(s) of 150'],
    ['bag(s) of 18'],
    ['bag(s) of 19'],
    ['bag(s) of 20'],
    ['bag(s) of 200'],
    ['bag(s) of 21'],
    ['bag(s) of 24'],
    ['bag(s) of 25'],
    ['bag(s) of 30'],
    ['bag(s) of 32'],
    ['bag(s) of 34'],
    ['bag(s) of 36'],
    ['bag(s) of 40'],
    ['bag(s) of 50'],
    ['bag(s) of 5000'],
    ['bag(s) of 60'],
    ['bag(s) of 6000'],
    ['bag(s) of 70'],
    ['bag(s) of 80'],
    ['becquerel(s)'],
    ['billion cells(s)'],
    ['blist pack(s) of 1'],
    ['blist pack(s) of 10'],
    ['blist pack(s) of 100'],
    ['blist pack(s) of 1000'],
    ['blist pack(s) of 108'],
    ['blist pack(s) of 110'],
    ['blist pack(s) of 112'],
    ['blist pack(s) of 12'],
    ['blist pack(s) of 120'],
    ['blist pack(s) of 13'],
    ['blist pack(s) of 14'],
    ['blist pack(s) of 140'],
    ['blist pack(s) of 15'],
    ['blist pack(s) of 16'],
    ['blist pack(s) of 160'],
    ['blist pack(s) of 168'],
    ['blist pack(s) of 170'],
    ['blist pack(s) of 175'],
    ['blist pack(s) of 18'],
    ['blist pack(s) of 180'],
    ['blist pack(s) of 182'],
    ['blist pack(s) of 2'],
    ['blist pack(s) of 20'],
    ['blist pack(s) of 200'],
    ['blist pack(s) of 21'],
    ['blist pack(s) of 210'],
    ['blist pack(s) of 220'],
    ['blist pack(s) of 24'],
    ['blist pack(s) of 240'],
    ['blist pack(s) of 25'],
    ['blist pack(s) of 27'],
    ['blist pack(s) of 273'],
    ['blist pack(s) of 28'],
    ['blist pack(s) of 29'],
    ['blist pack(s) of 3'],
    ['blist pack(s) of 30'],
    ['blist pack(s) of 300'],
    ['blist pack(s) of 310'],
    ['blist pack(s) of 32'],
    ['blist pack(s) of 33'],
    ['blist pack(s) of 36'],
    ['blist pack(s) of 380'],
    ['blist pack(s) of 396'],
    ['blist pack(s) of 4'],
    ['blist pack(s) of 40'],
    ['blist pack(s) of 42'],
    ['blist pack(s) of 45'],
    ['blist pack(s) of 48'],
    ['blist pack(s) of 49'],
    ['blist pack(s) of 5'],
    ['blist pack(s) of 50'],
    ['blist pack(s) of 500'],
    ['blist pack(s) of 51'],
    ['blist pack(s) of 55'],
    ['blist pack(s) of 56'],
    ['blist pack(s) of 560'],
    ['blist pack(s) of 6'],
    ['blist pack(s) of 60'],
    ['blist pack(s) of 63'],
    ['blist pack(s) of 64'],
    ['blist pack(s) of 68'],
    ['blist pack(s) of 7'],
    ['blist pack(s) of 70'],
    ['blist pack(s) of 72'],
    ['blist pack(s) of 74'],
    ['blist pack(s) of 75'],
    ['blist pack(s) of 8'],
    ['blist pack(s) of 80'],
    ['blist pack(s) of 84'],
    ['blist pack(s) of 9'],
    ['blist pack(s) of 90'],
    ['blist pack(s) of 91'],
    ['blist pack(s) of 96'],
    ['bottle(s) of 1'],
    ['bottle(s) of 10'],
    ['bottle(s) of 100'],
    ['bottle(s) of 1000'],
    ['bottle(s) of 10000'],
    ['bottle(s) of 103'],
    ['bottle(s) of 108'],
    ['bottle(s) of 11'],
    ['bottle(s) of 110'],
    ['bottle(s) of 1100'],
    ['bottle(s) of 112'],
    ['bottle(s) of 11500'],
    ['bottle(s) of 116'],
    ['bottle(s) of 12'],
    ['bottle(s) of 120'],
    ['bottle(s) of 1200'],
    ['bottle(s) of 12000'],
    ['bottle(s) of 124'],
    ['bottle(s) of 125'],
    ['bottle(s) of 126'],
    ['bottle(s) of 1260'],
    ['bottle(s) of 13'],
    ['bottle(s) of 130'],
    ['bottle(s) of 133'],
    ['bottle(s) of 135'],
    ['bottle(s) of 13500'],
    ['bottle(s) of 14'],
    ['bottle(s) of 140'],
    ['bottle(s) of 144'],
    ['bottle(s) of 145'],
    ['bottle(s) of 15'],
    ['bottle(s) of 150'],
    ['bottle(s) of 1500'],
    ['bottle(s) of 15000'],
    ['bottle(s) of 16'],
    ['bottle(s) of 160'],
    ['bottle(s) of 165'],
    ['bottle(s) of 168'],
    ['bottle(s) of 170'],
    ['bottle(s) of 175'],
    ['bottle(s) of 18'],
    ['bottle(s) of 180'],
    ['bottle(s) of 18000'],
    ['bottle(s) of 188'],
    ['bottle(s) of 189'],
    ['bottle(s) of 19'],
    ['bottle(s) of 190'],
    ['bottle(s) of 2'],
    ['bottle(s) of 20'],
    ['bottle(s) of 200'],
    ['bottle(s) of 2000'],
    ['bottle(s) of 20000'],
    ['bottle(s) of 21'],
    ['bottle(s) of 210'],
    ['bottle(s) of 216'],
    ['bottle(s) of 2160'],
    ['bottle(s) of 22'],
    ['bottle(s) of 220'],
    ['bottle(s) of 224'],
    ['bottle(s) of 225'],
    ['bottle(s) of 23'],
    ['bottle(s) of 230'],
    ['bottle(s) of 2300'],
    ['bottle(s) of 24'],
    ['bottle(s) of 240'],
    ['bottle(s) of 2400'],
    ['bottle(s) of 25'],
    ['bottle(s) of 250'],
    ['bottle(s) of 2500'],
    ['bottle(s) of 25000'],
    ['bottle(s) of 252'],
    ['bottle(s) of 26'],
    ['bottle(s) of 260'],
    ['bottle(s) of 265'],
    ['bottle(s) of 2650'],
    ['bottle(s) of 27'],
    ['bottle(s) of 270'],
    ['bottle(s) of 28'],
    ['bottle(s) of 280'],
    ['bottle(s) of 2800'],
    ['bottle(s) of 29'],
    ['bottle(s) of 290'],
    ['bottle(s) of 29000'],
    ['bottle(s) of 3'],
    ['bottle(s) of 30'],
    ['bottle(s) of 300'],
    ['bottle(s) of 3000'],
    ['bottle(s) of 30000'],
    ['bottle(s) of 3060'],
    ['bottle(s) of 32'],
    ['bottle(s) of 320'],
    ['bottle(s) of 3200'],
    ['bottle(s) of 325'],
    ['bottle(s) of 33'],
    ['bottle(s) of 330'],
    ['bottle(s) of 34'],
    ['bottle(s) of 35'],
    ['bottle(s) of 350'],
    ['bottle(s) of 3500'],
    ['bottle(s) of 36'],
    ['bottle(s) of 360'],
    ['bottle(s) of 3600'],
    ['bottle(s) of 365'],
    ['bottle(s) of 37'],
    ['bottle(s) of 375'],
    ['bottle(s) of 39'],
    ['bottle(s) of 390'],
    ['bottle(s) of 4'],
    ['bottle(s) of 40'],
    ['bottle(s) of 400'],
    ['bottle(s) of 4000'],
    ['bottle(s) of 40000'],
    ['bottle(s) of 41'],
    ['bottle(s) of 42'],
    ['bottle(s) of 4200'],
    ['bottle(s) of 44'],
    ['bottle(s) of 45'],
    ['bottle(s) of 450'],
    ['bottle(s) of 45000'],
    ['bottle(s) of 46'],
    ['bottle(s) of 47000'],
    ['bottle(s) of 48'],
    ['bottle(s) of 480'],
    ['bottle(s) of 5'],
    ['bottle(s) of 50'],
    ['bottle(s) of 500'],
    ['bottle(s) of 5000'],
    ['bottle(s) of 52'],
    ['bottle(s) of 520'],
    ['bottle(s) of 54'],
    ['bottle(s) of 540'],
    ['bottle(s) of 55'],
    ['bottle(s) of 550'],
    ['bottle(s) of 5500'],
    ['bottle(s) of 56'],
    ['bottle(s) of 5600'],
    ['bottle(s) of 58'],
    ['bottle(s) of 59'],
    ['bottle(s) of 6'],
    ['bottle(s) of 60'],
    ['bottle(s) of 600'],
    ['bottle(s) of 6000'],
    ['bottle(s) of 60000'],
    ['bottle(s) of 6030'],
    ['bottle(s) of 63'],
    ['bottle(s) of 64'],
    ['bottle(s) of 65'],
    ['bottle(s) of 66'],
    ['bottle(s) of 68'],
    ['bottle(s) of 7'],
    ['bottle(s) of 70'],
    ['bottle(s) of 700'],
    ['bottle(s) of 70000'],
    ['bottle(s) of 72'],
    ['bottle(s) of 720'],
    ['bottle(s) of 730'],
    ['bottle(s) of 74'],
    ['bottle(s) of 75'],
    ['bottle(s) of 750'],
    ['bottle(s) of 77'],
    ['bottle(s) of 78'],
    ['bottle(s) of 8'],
    ['bottle(s) of 80'],
    ['bottle(s) of 800'],
    ['bottle(s) of 8000'],
    ['bottle(s) of 81'],
    ['bottle(s) of 84'],
    ['bottle(s) of 85'],
    ['bottle(s) of 8500'],
    ['bottle(s) of 88'],
    ['bottle(s) of 9'],
    ['bottle(s) of 90'],
    ['bottle(s) of 900'],
    ['bottle(s) of 9000'],
    ['bottle(s) of 96'],
    ['bottle(s) of 9990'],
    ['box(s) of 1'],
    ['box(s) of 10'],
    ['box(s) of 100'],
    ['box(s) of 1000'],
    ['box(s) of 108'],
    ['box(s) of 110'],
    ['box(s) of 12'],
    ['box(s) of 120'],
    ['box(s) of 14'],
    ['box(s) of 144'],
    ['box(s) of 15'],
    ['box(s) of 150'],
    ['box(s) of 16'],
    ['box(s) of 168'],
    ['box(s) of 170'],
    ['box(s) of 18'],
    ['box(s) of 180'],
    ['box(s) of 190'],
    ['box(s) of 2'],
    ['box(s) of 20'],
    ['box(s) of 200'],
    ['box(s) of 21'],
    ['box(s) of 24'],
    ['box(s) of 25'],
    ['box(s) of 27'],
    ['box(s) of 28'],
    ['box(s) of 3'],
    ['box(s) of 30'],
    ['box(s) of 300'],
    ['box(s) of 32'],
    ['box(s) of 36'],
    ['box(s) of 3780'],
    ['box(s) of 38'],
    ['box(s) of 4'],
    ['box(s) of 40'],
    ['box(s) of 42'],
    ['box(s) of 45'],
    ['box(s) of 48'],
    ['box(s) of 5'],
    ['box(s) of 50'],
    ['box(s) of 54'],
    ['box(s) of 56'],
    ['box(s) of 58'],
    ['box(s) of 6'],
    ['box(s) of 60'],
    ['box(s) of 7'],
    ['box(s) of 72'],
    ['box(s) of 75'],
    ['box(s) of 8'],
    ['box(s) of 81'],
    ['box(s) of 88'],
    ['box(s) of 9'],
    ['box(s) of 90'],
    ['box(s) of 96'],
    ['can(s) of 100'],
    ['can(s) of 60'],
    ['canister(s) of 1'],
    ['canister(s) of 40'],
    ['canister(s) of 6'],
    ['canister(s) of 90'],
    ['caplet(s)'],
    ['capsule(s)'],
    ['cartridge(s) of 1'],
    ['cartridge(s) of 168'],
    ['cartridge(s) of 180'],
    ['cartridge(s) of 2'],
    ['cartridge(s) of 24'],
    ['cartridge(s) of 4'],
    ['cartridge(s) of 7'],
    ['cartridge(s) of 90'],
    ['cell(s)'],
    ['colony forming unit(s)'],
    ['cream(s)'],
    ['cup(s) of 50'],
    ['cup(s) of 8'],
    ['device(s)'],
    ['dose pk(s)'],
    ['dose-pack(s) of 12'],
    ['dose-pack(s) of 14'],
    ['dose-pack(s) of 21'],
    ['dose-pack(s) of 25'],
    ['dose-pack(s) of 28'],
    ['dose-pack(s) of 30'],
    ['dose-pack(s) of 33'],
    ['dose-pack(s) of 35'],
    ['dose-pack(s) of 37'],
    ['dose-pack(s) of 39'],
    ['dose-pack(s) of 4'],
    ['dose-pack(s) of 48'],
    ['dose-pack(s) of 49'],
    ['dose-pack(s) of 500'],
    ['dose-pack(s) of 51'],
    ['dose-pack(s) of 56'],
    ['dose-pack(s) of 98'],
    ['drop btl(s) of 30'],
    ['drop btl(s) of 60'],
    ['drop(s)'],
    ['drum(s) of 8000'],
    ['each'],
    ['film(s)'],
    ['flex cont(s) of 1'],
    ['g'],
    ['gigabecquerel(s)'],
    ['gram of carbohydrate(s)'],
    ['implant(s)'],
    ['inch(es)'],
    ['inhalation(s)'],
    ['insert(s)'],
    ['irrigation(s)'],
    ['jar(s) of 1'],
    ['jar(s) of 100'],
    ['jar(s) of 12'],
    ['jar(s) of 2'],
    ['jar(s) of 25'],
    ['jar(s) of 40'],
    ['jar(s) of 50'],
    ['jar(s) of 60'],
    ['jar(s) of 69'],
    ['jar(s) of 90'],
    ['kg'],
    ['kilobecquerel(s)'],
    ['kilohertz(s)'],
    ['kit(s) of 1'],
    ['kit(s) of 10'],
    ['kit(s) of 100'],
    ['kit(s) of 110'],
    ['kit(s) of 112'],
    ['kit(s) of 14'],
    ['kit(s) of 15'],
    ['kit(s) of 16'],
    ['kit(s) of 19'],
    ['kit(s) of 2'],
    ['kit(s) of 25'],
    ['kit(s) of 3'],
    ['kit(s) of 30'],
    ['kit(s) of 31'],
    ['kit(s) of 4'],
    ['kit(s) of 40'],
    ['kit(s) of 5'],
    ['kit(s) of 50'],
    ['kit(s) of 56'],
    ['kit(s) of 6'],
    ['kit(s) of 60'],
    ['kit(s) of 8'],
    ['kit-refill(s) of 100'],
    ['lesion(s)'],
    ['liquid(s)'],
    ['lollipop(s)'],
    ['lozenge(s)'],
    ['mCi'],
    ['mL'],
    ['megabecquerel(s)'],
    ['mg'],
    ['microcurie(s)'],
    ['microgram dietary folate equivalent(s)'],
    ['microgram(s)'],
    ['microliter(s)'],
    ['micromole(s)'],
    ['microunit(s)'],
    ['milliequivalent(s)'],
    ['milligram phenytoin equivalent(s)'],
    ['millimole(s)'],
    ['million cells'],
    ['million metric tons of coal equivalent(s)'],
    ['million plaque forming units(s)'],
    ['million units'],
    ['milliunit(s)'],
    ['nanogram(s)'],
    ['nebule(s)'],
    ['ophthalmic insert(s)'],
    ['ounce(s)'],
    ['package(s)'],
    ['packet(s)'],
    ['packet(s) of 1'],
    ['packet(s) of 10'],
    ['packet(s) of 100'],
    ['packet(s) of 11'],
    ['packet(s) of 110'],
    ['packet(s) of 116'],
    ['packet(s) of 12'],
    ['packet(s) of 120'],
    ['packet(s) of 125'],
    ['packet(s) of 14'],
    ['packet(s) of 144'],
    ['packet(s) of 15'],
    ['packet(s) of 150'],
    ['packet(s) of 16'],
    ['packet(s) of 18'],
    ['packet(s) of 180'],
    ['packet(s) of 2'],
    ['packet(s) of 20'],
    ['packet(s) of 21'],
    ['packet(s) of 24'],
    ['packet(s) of 240'],
    ['packet(s) of 25'],
    ['packet(s) of 250'],
    ['packet(s) of 28'],
    ['packet(s) of 3'],
    ['packet(s) of 30'],
    ['packet(s) of 300'],
    ['packet(s) of 32'],
    ['packet(s) of 36'],
    ['packet(s) of 360'],
    ['packet(s) of 4'],
    ['packet(s) of 40'],
    ['packet(s) of 42'],
    ['packet(s) of 44'],
    ['packet(s) of 48'],
    ['packet(s) of 5'],
    ['packet(s) of 50'],
    ['packet(s) of 500'],
    ['packet(s) of 51'],
    ['packet(s) of 54'],
    ['packet(s) of 56'],
    ['packet(s) of 6'],
    ['packet(s) of 60'],
    ['packet(s) of 70'],
    ['packet(s) of 72'],
    ['packet(s) of 75'],
    ['packet(s) of 8'],
    ['packet(s) of 80'],
    ['packet(s) of 9'],
    ['packet(s) of 90'],
    ['pad(s)'],
    ['patch(es)'],
    ['pellet(s)'],
    ['pf appli(s) of 1'],
    ['pf appli(s) of 100'],
    ['pf appli(s) of 12'],
    ['pf appli(s) of 14'],
    ['pf appli(s) of 2'],
    ['pf appli(s) of 25'],
    ['pf appli(s) of 3'],
    ['pf appli(s) of 4'],
    ['pf appli(s) of 5'],
    ['pf appli(s) of 50'],
    ['pf appli(s) of 6'],
    ['pf appli(s) of 60'],
    ['pf appli(s) of 72'],
    ['piece(s) of gum'],
    ['plaque forming unit(s)'],
    ['po pk(s)'],
    ['powder(s)'],
    ['puff(s)'],
    ['pump(s)'],
    ['recon(s)'],
    ['roll(s) of 12'],
    ['roll(s) of 24'],
    ['roll(s) of 36'],
    ['roll(s) of 8'],
    ['sachet(s)'],
    ['scoop(s)'],
    ['sliding scale dose(s)'],
    ['soln(s)'],
    ['solution(s)'],
    ['spray(s)'],
    ['squeez btl(s) of 1'],
    ['squeez btl(s) of 2'],
    ['squeez btl(s) of 3'],
    ['squeez btl(s) of 4'],
    ['startr pk(s)'],
    ['strip(s)'],
    ['suppositor(y/ies)'],
    ['suspension(s)'],
    ['syringe(s) of 1'],
    ['syringe(s) of 120'],
    ['syringe(s) of 2'],
    ['syringe(s) of 30'],
    ['syringe(s) of 50'],
    ['syringe(s) of 6'],
    ['syrup(s)'],
    ['tablet(s)'],
    ['tbsp'],
    ['thousand unit(s)'],
    ['towelette(s)'],
    ['tsp'],
    ['tube(s)'],
    ['tube(s) of 1'],
    ['tube(s) of 10'],
    ['tube(s) of 100'],
    ['tube(s) of 108'],
    ['tube(s) of 12'],
    ['tube(s) of 2'],
    ['tube(s) of 20'],
    ['tube(s) of 270'],
    ['tube(s) of 3'],
    ['tube(s) of 30'],
    ['tube(s) of 5'],
    ['tube(s) of 50'],
    ['unit(s)'],
    ['vaginal insert(s)'],
    ['vaginal ring(s)'],
    ['vector genome(s)'],
    ['vial(s)'],
    ['vial(s) of 1'],
    ['vial(s) of 10'],
    ['vial(s) of 100'],
    ['vial(s) of 108'],
    ['vial(s) of 12'],
    ['vial(s) of 135'],
    ['vial(s) of 14'],
    ['vial(s) of 144'],
    ['vial(s) of 2'],
    ['vial(s) of 20'],
    ['vial(s) of 24'],
    ['vial(s) of 25'],
    ['vial(s) of 28'],
    ['vial(s) of 3'],
    ['vial(s) of 30'],
    ['vial(s) of 32'],
    ['vial(s) of 36'],
    ['vial(s) of 4'],
    ['vial(s) of 5'],
    ['vial(s) of 6'],
    ['vial(s) of 60'],
    ['vial(s) of 80'],
    ['vial(s) of 81'],
    ['viral particle(s)'],
    ['wafer(s)'],
    ['x 10e14 vector genome(s)'],
    ['x 10e6 car-positive viable t cells(s)'],
    ['x 10e8 car-positive viable t cells(s)'],
])->execute();

    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        echo "m990101_000000_add_total_quantities_medications cannot be reverted.\n";

        return true;
    }
}