<?php

/**
 * Table for Patient
 */
class m210909_000000_Patient extends \yii\db\Migration
{
    public function up()
    {
        $this->createTable('{{%patients}}', [
            'address1' => text,
            'address2' => text,
            'agriculturalworker' => text,
            'agriculturalworkertype' => text,
            'balances' => text,
            'caresummarydeliverypreference' => text,
            'city' => text,
            'claimbalancedetails' => text,
            'confidentialitycode' => text,
            'consenttocall' => text,
            'consenttotext' => text,
            'contacthomephone' => text,
            'contactmobilephone' => text,
            'contactname' => text,
            'contactpreference' => text,
            'contactpreference_announcement_email' => text,
            'contactpreference_announcement_phone' => text,
            'contactpreference_announcement_sms' => text,
            'contactpreference_appointment_email' => text,
            'contactpreference_appointment_phone' => text,
            'contactpreference_appointment_sms' => text,
            'contactpreference_billing_email' => text,
            'contactpreference_billing_phone' => text,
            'contactpreference_billing_sms' => text,
            'contactpreference_lab_email' => text,
            'contactpreference_lab_phone' => text,
            'contactpreference_lab_sms' => text,
            'contactrelationship' => text,
            'countrycode' => text,
            'countrycode3166' => text,
            'customfields' => text,
            'deceaseddate' => text,
            'defaultpharmacyncpdpid' => text,
            'departmentid' => text,
            'dob' => text,
            'donotcallyn' => text,
            'driverslicenseexpirationdate' => text,
            'driverslicensenumber' => text,
            'driverslicensestateid' => text,
            'driverslicenseurl' => text,
            'driverslicenseyn' => text,
            'email' => text,
            'emailexistsyn' => text,
            'employeraddress' => text,
            'employercity' => text,
            'employerfax' => text,
            'employerid' => text,
            'employername' => text,
            'employerphone' => text,
            'employerstate' => text,
            'employerzip' => text,
            'ethnicitycode' => text,
            'firstappointment' => text,
            'firstname' => text,
            'guarantoraddress1' => text,
            'guarantoraddress2' => text,
            'guarantoraddresssameaspatient' => text,
            'guarantorcity' => text,
            'guarantorcountrycode' => text,
            'guarantorcountrycode3166' => text,
            'guarantordob' => text,
            'guarantoremail' => text,
            'guarantoremployerid' => text,
            'guarantorfirstname' => text,
            'guarantorlastname' => text,
            'guarantormiddlename' => text,
            'guarantorphone' => text,
            'guarantorrelationshiptopatient' => text,
            'guarantorssn' => text,
            'guarantorstate' => text,
            'guarantorsuffix' => text,
            'guarantorzip' => text,
            'guardianfirstname' => text,
            'guardianlastname' => text,
            'guardianmiddlename' => text,
            'guardiansuffix' => text,
            'hasmobileyn' => text,
            'hierarchicalcode' => text,
            'homeboundyn' => text,
            'homeless' => text,
            'homelesstype' => text,
            'homephone' => text,
            'industrycode' => text,
            'insurances' => text,
            'language6392code' => text,
            'lastappointment' => text,
            'lastemail' => text,
            'lastname' => text,
            'maritalstatus' => text,
            'maritalstatusname' => text,
            'medicationhistoryconsentverified' => text,
            'middlename' => text,
            'mobilecarrierid' => text,
            'mobilephone' => text,
            'nextkinname' => text,
            'nextkinphone' => text,
            'nextkinrelationship' => text,
            'notes' => text,
            'occupationcode' => text,
            'onlinestatementonlyyn' => text,
            'patientid' => text,
            'patientphotourl' => text,
            'patientphotoyn' => text,
            'portalaccessgiven' => text,
            'portalsignatureonfile' => text,
            'portalstatus' => text,
            'portaltermsonfile' => text,
            'povertylevelcalculated' => text,
            'povertylevelfamilysize' => text,
            'povertylevelfamilysizedeclined' => text,
            'povertylevelincomedeclined' => text,
            'povertylevelincomepayperiod' => text,
            'povertylevelincomeperpayperiod' => text,
            'povertylevelincomerangedeclined' => text,
            'preferredname' => text,
            'primarydepartmentid' => text,
            'primaryproviderid' => text,
            'privacyinformationverified' => text,
            'publichousing' => text,
            'race' => text,
            'racename' => text,
            'referralsourceid' => text,
            'registrationdate' => text,
            'schoolbasedhealthcenter' => text,
            'sex' => text,
            'ssn' => text,
            'state' => text,
            'status' => text,
            'suffix' => text,
            'veteran' => text,
            'workphone' => text,
            'zip' => text,
            'external_id' => $this->string(),
            'id' => $this->primaryKey(),
        ]);

        // TODO generate foreign keys
    }

    public function down()
    {
        $this->dropTable('{{%patients}}');
    }
}
